-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 23:57:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbcaxtop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbcaxtop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcaxtop` DEFAULT CHARACTER SET utf8 ;
USE `dbcaxtop` ;

-- -----------------------------------------------------
-- Table `dbcaxtop`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcaxtop`.`entrada` (
  `documento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `dataInclusao` DATE NULL,
  `valor` FLOAT NULL,
  PRIMARY KEY (`documento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

------------------------------------------------------------------------------------------------

-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 23:57:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbcaxtop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbcaxtop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcaxtop` DEFAULT CHARACTER SET utf8 ;
USE `dbcaxtop` ;

-- -----------------------------------------------------
-- Table `dbcaxtop`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcaxtop`.`saida` (
  `documento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `dataInclusao` DATE NULL,
  `valor` FLOAT NULL,
  PRIMARY KEY (`documento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
